name: Check code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: ./.github/workflows/initialize.yml
      - name: Check eslint
        run: yarn lint